CREATE DATABASE universe;
CREATE TABLE galaxy();
CREATE TABLE star();
CREATE TABLE planet();
CREATE TABLE moon();
ALTER TABLE galaxy ADD COLUMN galaxy_id SERIAL NOT NULL;
ALTER TABLE galaxy ADD PRIMARY KEY (galaxy_id);
ALTER TABLE star ADD COLUMN star_id SERIAL NOT NULL;
ALTER TABLE star ADD PRIMARY KEY (star_id);
ALTER TABLE planet ADD COLUMN planet_id SERIAL NOT NULL;
ALTER TABLE planet ADD PRIMARY KEY (planet_id);
ALTER TABLE moon ADD COLUMN moon_id SERIAL NOT NULL;
ALTER TABLE moon ADD PRIMARY KEY (moon_id);
CREATE TABLE blackhole();
ALTER TABLE blackhole ADD PRIMARY KEY (blackhole_id);
ALTER TABLE blackhole ADD COLUMN blackhole_id SERIAL NOT NULL;
ALTER TABLE galaxy ADD COLUMN name VARCHAR(30) UNIQUE NOT NULL;
ALTER TABLE blackhole  ADD COLUMN name VARCHAR(30) UNIQUE NOT NULL;
ALTER TABLE star ADD COLUMN name VARCHAR(30) UNIQUE NOT NULL;
ALTER TABLE planet ADD COLUMN name VARCHAR(30) UNIQUE NOT NULL;
ALTER TABLE moon ADD COLUMN name VARCHAR(30) UNIQUE NOT NULL;
ALTER TABLE galaxy ADD COLUMN size_ly INT;
ALTER TABLE star ADD COLUMN distance_from_earth INT;
ALTER TABLE planet ADD COLUMN has_moon BOOLEAN;
ALTER TABLE moon ADD COLUMN has_atmosphere BOOLEAN;
ALTER TABLE moon ADD COLUMN size NUMERIC(7,2);
ALTER TABLE blackhole ADD COLUMN distance_ly INT;
ALTER TABLE galaxy ADD COLUMN galaxy_type TEXT;
ALTER TABLE galaxy ADD COLUMN distance_from_earth INT;
ALTER TABLE star ADD COLUMN type VARCHAR(30);
ALTER TABLE planet ADD COLUMN has_atmosphere BOOLEAN;
ALTER TABLE star ADD COLUMN galaxy_id INT;
ALTER TABLE star ADD CONSTRAINT fk_star_galaxy_id FOREIGN KEY (galaxy_id) REFERENCES galaxy (galaxy_id);
ALTER TABLE planet ADD COLUMN star_id INT;
ALTER TABLE planet ADD CONSTRAINT fk_planet_star_id FOREIGN KEY (star_id) REFERENCES star (star_id);
ALTER TABLE moon ADD COLUMN planet_id INT;
ALTER TABLE moon ADD CONSTRAINT fk_moon_planet_id FOREIGN KEY (planet_id) REFERENCES planet (planet_id);
INSERT INTO blackhole (name, distance_ly) VALUES ('Gaia BH1',1560);
INSERT INTO blackhole (name, distance_ly) VALUES ('Cygnus X-1',7300);
INSERT INTO blackhole (name, distance_ly) VALUES ('Sagittarius A*',25600);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth) VALUES ('Milkyway', 87400, 'spiral', 0);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth) VALUES ('Andromeda', 110000, 'spiral', 2480000);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth) VALUES (' Antennae Galaxies', 500000, 'spiral', 65000000);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth)VALUES ('Sombrero Galaxy', 49000, 'elliptical', 29000000);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth)VALUES ('Triangulum Galaxy', 61120, 'spiral', 2730000);
INSERT INTO galaxy (name, size_ly, galaxy_type, distance_from_earth)VALUES ('Whirlpool Galaxy', 76900, 'spiral', 31000000);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES ('Sun', 0, 'G-Type Main-Sequence', 1);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES (‘Alpha Centauri A', 4, 'G-Type Main-Sequence', 1);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES (‘Alpha Centauri B', 4, 'G-Type Main-Sequence', 1);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES (‘Proxima Centauri', 4, ‘Red Dwarf’, 1);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES (‘Sirius A’, 9, ‘Main Sequence Blue', 1);
INSERT INTO star (name, distance_from_earth, type, galaxy_id) VALUES ('Sirius B', 9, 'White Dwarf', 1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Earth', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Mercury', 'no','no',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Venus', 'no','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Mars', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Jupiter', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Saturn', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Uranus', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Neptune', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Pluto', 'yes','yes',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Sedna', 'no','no',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Haumea', 'no','no',1);
INSERT INTO planet (name, has_moon, has_atmosphere, star_id) VALUES ('Orcus', 'no','no',1);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Moon','no',1079.60,1);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Phobos','no',7.00,4);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Deimos','no',3.85,4);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Titan','yes',1599.90,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Ganymede','no',1636.80,5);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Callisto','no',1497.70,5);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Io','no',1131.70,5);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Europa','no',969.84,5);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Triton','yes',840.96,8);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Rhea','no',474.60,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Iapetus','no',457.00,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Dione','no',348.84,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Tethys','no',331.00,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Titania','no',1000.00,7);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Oberon','no',946.00,7);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Umbriel','no',750.00,7);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Ariel','no',720.00,7);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Charon','no',750.00,9);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Enceladus','no',314.00,6);
INSERT INTO moon (name, has_atmosphere, size, planet_id) VALUES ('Mimas','no',123.00,6);
